/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaventas;

import com.itextpdf.text.Document;
import com.itextpdf.text.Image;
import static com.itextpdf.text.Image.RIGHT;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author rancagua
 */
public class JIDetalle extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIDetalle
     */
    public JIDetalle() {
        initComponents();
        Cargar();
        timer.start();
    }
    ButtonGroup grupo1 = new ButtonGroup();
    ConexionBD conexion = new ConexionBD();
    Connection cn = conexion.conectar();
    
    public void GrupoBotones(){
            grupo1.add(hoy);
            grupo1.add(todas);
            grupo1.add(personalizada);
            todas.setSelected(true);
    }
    Timer timer = new Timer (1000, new ActionListener ()
{
    public void actionPerformed(ActionEvent e)
    {
        GrupoBotones();
        //bloquear fechas
        dDia.setEnabled(false);
        dMes.setEnabled(false);
        dAño.setEnabled(false);
        hDia.setEnabled(false);
        hMes.setEnabled(false);
        hAño.setEnabled(false);
        btnFiltro.setEnabled(false);
        timer.stop();
     }
});
    
    public void Cargar(){
        //tomar modelo de la tabla
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        //abrir conexion
        conexion.conectar();
        try {
                //Crear consulta para buscar empleado segun rut
                String Query = "select * from venta";
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(Query);
                while(rs.next())
                {
                    String numero = rs.getString("NUMERO");
                    String fecha = rs.getString("FECHA");
                    String empleado = rs.getString("EMPLEADO");
                    String cliente = rs.getString("CLIENTE");
                    String total = rs.getString("TOTAL");
                    Object fila[] = {numero,fecha,empleado,cliente,total};
                    m.addRow(fila);
                }
                conexion.desconectar();

            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    //Limpiar tabla 
    public void LimpiarT(){
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Fecha", "Empleado", "Cliente", "Total"
            }
        ));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        Fecha3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Fecha2 = new javax.swing.JLabel();
        personalizada = new javax.swing.JRadioButton();
        hoy = new javax.swing.JRadioButton();
        todas = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnExcel = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        hMes = new javax.swing.JComboBox();
        hDia = new javax.swing.JComboBox();
        hAño = new javax.swing.JComboBox();
        dDia = new javax.swing.JComboBox();
        dMes = new javax.swing.JComboBox();
        dAño = new javax.swing.JComboBox();
        btnFiltro = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        fondo = new javax.swing.JLabel();

        setTitle("Detalle de ventas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Fecha", "Empleado", "Cliente", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 30, 710, 402));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 330, 10));

        Fecha3.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        Fecha3.setForeground(new java.awt.Color(255, 255, 255));
        Fecha3.setText("BUSQUEDA");
        getContentPane().add(Fecha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 210, 50));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 480, 10));

        Fecha2.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        Fecha2.setForeground(new java.awt.Color(255, 255, 255));
        Fecha2.setText("REPORTES");
        getContentPane().add(Fecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 220, 50));

        personalizada.setBackground(new java.awt.Color(0, 102, 153));
        personalizada.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        personalizada.setForeground(new java.awt.Color(255, 255, 255));
        personalizada.setText("PERSONALIZADA");
        personalizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalizadaActionPerformed(evt);
            }
        });
        getContentPane().add(personalizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 180, -1));

        hoy.setBackground(new java.awt.Color(0, 102, 153));
        hoy.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        hoy.setForeground(new java.awt.Color(255, 255, 255));
        hoy.setText("HOY");
        hoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoyActionPerformed(evt);
            }
        });
        getContentPane().add(hoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 90, -1));

        todas.setBackground(new java.awt.Color(0, 102, 153));
        todas.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        todas.setForeground(new java.awt.Color(255, 255, 255));
        todas.setText("TODAS");
        todas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todasActionPerformed(evt);
            }
        });
        getContentPane().add(todas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 90, -1));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HASTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 70, -1));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DESDE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btnExcel.jpg"))); // NOI18N
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 120, 120));

        btnPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btnPDF.jpg"))); // NOI18N
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });
        getContentPane().add(btnPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 120, 120));

        hMes.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        hMes.setForeground(new java.awt.Color(0, 102, 153));
        hMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        hMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hMesActionPerformed(evt);
            }
        });
        getContentPane().add(hMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        hDia.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        hDia.setForeground(new java.awt.Color(0, 102, 153));
        hDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(hDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 40, -1));

        hAño.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        hAño.setForeground(new java.awt.Color(0, 102, 153));
        hAño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017" }));
        getContentPane().add(hAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        dDia.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        dDia.setForeground(new java.awt.Color(0, 102, 153));
        dDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(dDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 40, -1));

        dMes.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        dMes.setForeground(new java.awt.Color(0, 102, 153));
        dMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        dMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dMesActionPerformed(evt);
            }
        });
        getContentPane().add(dMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        dAño.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        dAño.setForeground(new java.awt.Color(0, 102, 153));
        dAño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017" }));
        getContentPane().add(dAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        btnFiltro.setBackground(new java.awt.Color(255, 255, 255));
        btnFiltro.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        btnFiltro.setForeground(new java.awt.Color(0, 102, 153));
        btnFiltro.setText("Buscar");
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 60, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 480, 10));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Layout.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1275, 493));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoyActionPerformed
        //bloquear fechas
        dDia.setEnabled(false);
        dMes.setEnabled(false);
        dAño.setEnabled(false);
        hDia.setEnabled(false);
        hMes.setEnabled(false);
        hAño.setEnabled(false);
        btnFiltro.setEnabled(false);
        //Limpiar tabla
        LimpiarT();
        //Fecha actual para query
        //Crear instancia calendario
        Calendar cal = Calendar.getInstance();
        //Asignar fecha a label 
        String FHoy = ( + cal.get(Calendar.DATE) + "/" + (cal.get(Calendar.MONTH) + 1) + "/" + cal.get(Calendar.YEAR));
        
        //tomar modelo de la tabla
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        //abrir conexion
        conexion.conectar();
        try {
                //Crear consulta para buscar empleado segun rut
                String Query = "select * from venta where(Fecha = '" + FHoy + "')";
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(Query);
                while(rs.next())
                {
                    String numero = rs.getString("NUMERO");
                    String fecha = rs.getString("FECHA");
                    String empleado = rs.getString("EMPLEADO");
                    String cliente = rs.getString("CLIENTE");
                    String total = rs.getString("TOTAL");
                    Object fila[] = {numero,fecha,empleado,cliente,total};
                    m.addRow(fila);
                }
                conexion.desconectar();
                
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
    }//GEN-LAST:event_hoyActionPerformed

    private void todasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todasActionPerformed
        LimpiarT();
        Cargar();
        //bloquear fechas
        dDia.setEnabled(false);
        dMes.setEnabled(false);
        dAño.setEnabled(false);
        hDia.setEnabled(false);
        hMes.setEnabled(false);
        hAño.setEnabled(false);
        btnFiltro.setEnabled(false);
    }//GEN-LAST:event_todasActionPerformed

    private void personalizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalizadaActionPerformed
        //desbloquear fechas
        dDia.setEnabled(true);
        dMes.setEnabled(true);
        dAño.setEnabled(true);
        hDia.setEnabled(true);
        hMes.setEnabled(true);
        hAño.setEnabled(true);
        btnFiltro.setEnabled(true);
    }//GEN-LAST:event_personalizadaActionPerformed

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
       JFileChooser examinar = new JFileChooser();
       examinar.showSaveDialog(this);
       File guarda = examinar.getSelectedFile();
       
       try{
       if(guarda !=null){
        PdfPTable tabla = new PdfPTable(5);
        FileOutputStream archivo = new FileOutputStream(guarda+".pdf");
        Document documento = new Document();
        PdfWriter.getInstance(documento, archivo);
        documento.open();
        
        // Agregar imagen
        //Image image1 = Image.getInstance("C:\\Users\\jhonny\\Documents\\Visual Studio 2013\\Projects\\YourColor\\YourColor\\Resources\\logo.png");
        //image1.scalePercent(50f);
        //image1.setAlignment(RIGHT);
        
        //documento.add(image1);
        
        //tomar modelo de la tabla
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        
        int f = 0;
            String Numero;
            String Fecha;
            String Empleado;
            String Cliente;
            String Total;
            
                while(f<(m.getRowCount()))
                {
                    Numero = m.getValueAt(f, 0).toString();
                    Fecha = m.getValueAt(f, 1).toString(); 
                    Empleado = m.getValueAt(f, 2).toString();
                    Cliente = m.getValueAt(f, 3).toString(); 
                    Total = m.getValueAt(f, 4).toString();         
                    //escribir fila en el archivo
                        tabla.addCell(Numero);
                        tabla.addCell(Fecha);                  
                        tabla.addCell(Empleado);
                        tabla.addCell(Cliente);
                        tabla.addCell(Total);
                    //Aumentar la variable
                    f++;
                }
                //Añadir Tabla
                    documento.add(tabla);
        documento.close();
        archivo.close();
         JOptionPane.showMessageDialog(null,
         "El archivo se a guardado Exitosamente",
             "Información",JOptionPane.INFORMATION_MESSAGE);
    }
       }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error Al crear PDF");
        }            
    }//GEN-LAST:event_btnPdfActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
       JFileChooser examinar = new JFileChooser();
       examinar.showSaveDialog(this);
       File guarda = examinar.getSelectedFile();
       
       try{
       if(guarda !=null){
           //Obtener modelo de la tabla    
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
            //Crear archivo de texto
            PrintWriter archivo = new PrintWriter(new FileWriter(guarda + ".csv"));
            int f = 0;
            String Numero;
            String Fecha;
            String Empleado;
            String Cliente;
            String Total;
            archivo.println("NUMERO;"+"FECHA;"+"EMPLEADO;"+"CLIENTE;"+"TOTAL");
                while(f<(m.getRowCount()))
                {
                    Numero = m.getValueAt(f, 0).toString();
                    Fecha = m.getValueAt(f, 1).toString(); 
                    Empleado = m.getValueAt(f, 2).toString();
                    Cliente = m.getValueAt(f, 3).toString(); 
                    Total = m.getValueAt(f, 4).toString(); 
                    //escribir fila en el archivo
                    archivo.println(Numero + ";" + Fecha + ";" + Empleado + ";" + Cliente + ";" + Total);
                    //Aumentar la variable
                    f++;
                }
                //Cerrar el arhivo
                archivo.close();
                
                JOptionPane.showMessageDialog(null,
         "El archivo se a guardado Exitosamente",
             "Información",JOptionPane.INFORMATION_MESSAGE);
       }
       }catch(Exception e){
                    JOptionPane.showMessageDialog(this, e.toString());
                    } 
    }//GEN-LAST:event_btnExcelActionPerformed

    private void dMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dMesActionPerformed
        
    }//GEN-LAST:event_dMesActionPerformed

    private void hMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hMesActionPerformed
        
    }//GEN-LAST:event_hMesActionPerformed

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
        String desde = (String) dDia.getSelectedItem() +"/"+ (String) dMes.getSelectedItem() +"/"+ (String) dAño.getSelectedItem();
        String hasta = (String) hDia.getSelectedItem() +"/"+ (String) hMes.getSelectedItem() +"/"+ (String) hAño.getSelectedItem();
        
        //limpar jtable
            LimpiarT();
             //tomar modelo de la tabla
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        //abrir conexion
        conexion.conectar();
        try {
                //Crear consulta para buscar empleado segun rut
                String Query = ("select * from venta where(Fecha between '" + desde + "' and '" + hasta + "' )");
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(Query);
                while(rs.next())
                {
                    String numero = rs.getString("NUMERO");
                    String fecha = rs.getString("FECHA");
                    String empleado = rs.getString("EMPLEADO");
                    String cliente = rs.getString("CLIENTE");
                    String total = rs.getString("TOTAL");
                    Object fila[] = {numero,fecha,empleado,cliente,total};
                    m.addRow(fila);
                }
                conexion.desconectar();
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnFiltroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fecha2;
    private javax.swing.JLabel Fecha3;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnFiltro;
    private javax.swing.JButton btnPdf;
    private javax.swing.JComboBox dAño;
    private javax.swing.JComboBox dDia;
    private javax.swing.JComboBox dMes;
    private javax.swing.JLabel fondo;
    private javax.swing.JComboBox hAño;
    private javax.swing.JComboBox hDia;
    private javax.swing.JComboBox hMes;
    private javax.swing.JRadioButton hoy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton personalizada;
    private javax.swing.JRadioButton todas;
    // End of variables declaration//GEN-END:variables
}
