/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaventas;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author rancagua
 */
public class JIEmpleados extends javax.swing.JInternalFrame {
DefaultTableModel model;
Connection conn;
Statement sent;
    /**
     * Creates new form JIEmpleados
     */
    public JIEmpleados() {
        initComponents();
        mostrarDatos("");
        limitar();
        //Llamar validacion solo numeros a los text field correspondientes
        SNumeros(tfRut);
        SNumeros(tfFono);
        SLetras(tfNombre);
        SLetras(tfApellido);
    }
    //Metodo que limita los caracteres de los Txt Field
    public void limitar(){
        tfRut.setDocument(new Limitador(tfRut, 8));
        tfVerificador.setDocument(new Limitador(tfVerificador, 1));
        tfNombre.setDocument(new Limitador(tfNombre, 30));
        tfApellido.setDocument(new Limitador(tfApellido, 30));
        tfContraseña.setDocument(new Limitador (tfContraseña,30));
        tfFono.setDocument(new Limitador(tfFono, 8));
        tfCorreo.setDocument(new Limitador(tfCorreo, 50));
        tfDireccion.setDocument(new Limitador(tfDireccion, 60));
    }
    
      //limpiar campos
    public void Limpiar(){
    this.tfBusqueda.setText("");
    this.tfCorreo.setText("");
    this.tfDireccion.setText("");
    this.tfFono.setText("");
    this.tfNombre.setText("");
    this.tfRut.setText("");
    this.tfVerificador.setText("");
    this.tfContraseña.setText("");
    this.tfApellido.setText("");
    this.tfRut.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        tfRut = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        tfBusqueda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfVerificador = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        tfContraseña = new javax.swing.JTextField();
        tfCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfFono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jMenuItem1.setText("Editar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfRut.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        tfRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRutActionPerformed(evt);
            }
        });
        getContentPane().add(tfRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 50, 208, -1));

        btnEliminar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(51, 102, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 197, 128, -1));

        tfBusqueda.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        tfBusqueda.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfBusquedaCaretUpdate(evt);
            }
        });
        tfBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(tfBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 623, -1));

        jLabel3.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("APELLIDO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 163, -1, -1));

        tfVerificador.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        getContentPane().add(tfVerificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 40, -1));

        btnEditar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(51, 102, 255));
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 254, 128, -1));

        jLabel6.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FLTRAR");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        tfNombre.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        getContentPane().add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 105, 208, -1));

        jLabel8.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DIRECCION");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 388, -1, -1));

        tfDireccion.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        getContentPane().add(tfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 385, 346, -1));

        tfApellido.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        tfApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(tfApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 160, 208, -1));

        tfContraseña.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        getContentPane().add(tfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 215, 208, -1));

        tfCorreo.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        getContentPane().add(tfCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 330, 346, -1));

        jLabel4.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONTRASEÑA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 218, -1, -1));

        tfFono.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        getContentPane().add(tfFono, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 275, 208, -1));

        jLabel7.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CORREO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 333, -1, -1));

        jTable1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut", "Verificador", "Nombre", "Apellido", "Fono", "Correo", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 700, 347));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RUT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 53, -1, -1));

        btnAgregar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(51, 102, 255));
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 140, 128, -1));

        jLabel5.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FONO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 278, -1, -1));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 108, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Layout.jpg"))); // NOI18N
        fondo.setText("Empleados");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRutActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Crear instancia: conexion
        ConexionBD conexion = new ConexionBD();
        Connection con = conexion.conectar();
        //
        int fila = jTable1.getSelectedRow();
        //
        String rut="";
        //
        rut=jTable1.getValueAt(fila, 0).toString();
        try{
            //sentencia para eliminar los datos
            PreparedStatement pst = con.prepareStatement("DELETE FROM empleado WHERE Rut='"+rut+"'");
            pst.executeUpdate();
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut","Verificador", "Nombre", "Apellido", "Fono", "Correo", "Direccion"
            }
        )
        );
            mostrarDatos("");
            Limpiar();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tfBusquedaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfBusquedaCaretUpdate
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut","Verificador", "Nombre", "Apellido", "Fono", "Correo", "Direccion"
            }
        )
        );

        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        try{
            // Conectar a la BD
            ConexionBD conexion = new ConexionBD();
            Connection con = conexion.conectar();
            //Consulta a ejecutar
            String     sql = ("SELECT Rut, Verificador, Nombre, Apellido, Fono, Correo, Direccion FROM empleado WHERE (Rut like '%"+tfBusqueda.getText()+"%') or (Nombre like '%"+tfBusqueda.getText()+"%') or (Apellido like '%"+tfBusqueda.getText()+"%')");
            //Preparar la consulta
            Statement st = con.createStatement();
            //Ejecutar consulta
            ResultSet rs = st.executeQuery(sql);
            //Mostrar los datos
            while(rs.next()){
                String rut = rs.getString("Rut");
                String verif = rs.getString("Verificador");
                String nombre = rs.getString("Nombre");
                String ape = rs.getString("Apellido");
                String fono = rs.getString("Fono");
                String correo = rs.getString("Correo");
                String direcc = rs.getString("Direccion");
                Object fila []  = {rut, verif, nombre, ape, fono, correo, direcc};
                m.addRow(fila);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tfBusquedaCaretUpdate

    private void tfBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBusquedaActionPerformed

    }//GEN-LAST:event_tfBusquedaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Crear instancia: conexion
        ConexionBD conexion = new ConexionBD();
        Connection con = conexion.conectar();
        try{
            //sentencia para editar los datos
            PreparedStatement pst = con.prepareStatement("UPDATE empleado SET Rut='"+tfRut.getText()+"',Verificador='"+tfVerificador.getText()+"',Nombre='"+tfNombre.getText()+"',Apellido='"+tfApellido.getText()+"',Contraseña='"+tfContraseña.getText()+"',Fono='"+tfFono.getText()+"',Correo='"+tfCorreo.getText()+"',Direccion='"+tfDireccion.getText()+"' WHERE Rut='"+tfRut.getText()+"'");
            pst.executeUpdate();
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut","Verificador", "Nombre", "Apellido", "Fono", "Correo", "Direccion"
            }
        )
        );
                    mostrarDatos("");
                    Limpiar();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tfApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApellidoKeyTyped

    }//GEN-LAST:event_tfApellidoKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // Crear instancia: conexion
        ConexionBD conexion = new ConexionBD();
        Connection con = conexion.conectar();

        try{
            //iniciar la conexion
            conexion.conectar();
            Statement st = con.createStatement();
            //Sentencia para ingresar proveedores en la BD
            st.executeUpdate("INSERT INTO empleado (Rut,Verificador,Nombre,Apellido,Contraseña,Fono,Correo,Direccion,Perfil) VALUES('"+tfRut.getText()+"','"+tfVerificador.getText()+"','"+tfNombre.getText()+"','"+tfApellido.getText()+"','"+tfContraseña.getText()+"','"+tfFono.getText()+"','"+tfCorreo.getText()+"','"+tfDireccion.getText()+"','1')");
jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut","Verificador", "Nombre", "Apellido", "Fono", "Correo", "Direccion"
            }
        )
        );
mostrarDatos("");
Limpiar();
        }catch(Exception ex){

            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Seleccionar fila para editar 
        int fila=jTable1.getSelectedRow();
        if (fila>=0){
            //Seleeciona la fila para mostrarla en el Text Field correspondiente
            tfRut.setText(jTable1.getValueAt(fila,0).toString());
            tfVerificador.setText(jTable1.getValueAt(fila,1).toString());
            tfNombre.setText(jTable1.getValueAt(fila,2).toString());
            tfApellido.setText(jTable1.getValueAt(fila,3).toString());
            tfFono.setText(jTable1.getValueAt(fila,4).toString());
            tfCorreo.setText(jTable1.getValueAt(fila,5).toString());
            tfDireccion.setText(jTable1.getValueAt(fila,6).toString());
            
        }
        else{
        JOptionPane.showMessageDialog(null,"No selecciono fila");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    //Metodo para validar solo letras
    public void SLetras (JTextField a){
    //permite hacer la llamada al evento
        //KeyAdapter es una clase abstracta que se adapta para recibir los eventos del teclado
        a.addKeyListener(new KeyAdapter() {
            //Evento a utilizar
            public void keyTyped(KeyEvent e){
            //La variable char extrae la variable que se ingresa
                char c=e.getKeyChar();
                if(Character.isDigit(c)){
                //Sonido en caso que se ingrese un caracter no admitido
                getToolkit().beep();
                e.consume();
                }
            }
        });
    }
    
    //Metodo para validar solo numeros
    public void SNumeros (JTextField a){
    //permite hacer la llamada al evento
        //KeyAdapter es una clase abstracta que se adapta para recibir los eventos del teclado
        a.addKeyListener(new KeyAdapter() {
            //Evento a utilizar
            public void keyTyped(KeyEvent e){
            //La variable char extrae la variable que se ingresa
                char c=e.getKeyChar();
                if(Character.isLetter(c)){
                //Sonido en caso que se ingrese un caracter no admitido
                getToolkit().beep();
                e.consume();
                }
            }
        });
    }
    
    private void mostrarDatos(String valor){
    // Crear instancia: conexion
        ConexionBD conexion = new ConexionBD();
        Connection con = conexion.conectar();
    //capturar modelo de la tabla
    DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        jTable1.setModel(m);
    //Acumular sentencia a ejecutar
        String sql="";
        //condicion que compara el valor que se recibe con la sentencia
        if(valor.equals("")){
            sql="SELECT Rut, Verificador, Nombre, Apellido, Fono, Correo, Direccion FROM empleado";
        }else{
            sql="SELECT Rut, Verificador, Nombre, Apellido, Fono, Correo, Direccion FROM empleado WHERE RUT='"+valor+"'";
        }
    String [] datos = new String[7];
    try{
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                m.addRow(datos);
            }
            jTable1.setModel(m);
    }catch(SQLException ex){
    Logger.getLogger(JIProveedores.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfBusqueda;
    private javax.swing.JTextField tfContraseña;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfFono;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfRut;
    private javax.swing.JTextField tfVerificador;
    // End of variables declaration//GEN-END:variables
}
