/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaventas;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author rancagua
 */
public class JIProveedores extends javax.swing.JInternalFrame {
DefaultTableModel model;
Connection conn;
Statement sent;
    /**
     * Creates new form JIProveedores
     */
    public JIProveedores() {
        initComponents();
        mostrarDatos("");
        limitar();
        //Llamar validacion solo numeros a los text field correspondientes
        SNumeros(tfRut);
        SNumeros(tfFono);
    }
    
    //limpiar campos
    public void Limpiar(){
    this.tfBusqueda.setText("");
    this.tfCorreo.setText("");
    this.tfDireccion.setText("");
    this.tfFono.setText("");
    this.tfNombre.setText("");
    this.tfRut.setText("");
    this.tfVerificador.setText("");
    this.tfRut.requestFocus();
    }
    //Metodo que limita los caracteres de los Txt Field
    public void limitar(){
        tfRut.setDocument(new Limitador(tfRut, 8));
        tfVerificador.setDocument(new Limitador(tfVerificador, 1));
        tfNombre.setDocument(new Limitador(tfNombre, 30));
        tfFono.setDocument(new Limitador(tfFono, 8));
        tfCorreo.setDocument(new Limitador(tfCorreo, 50));
        tfDireccion.setDocument(new Limitador(tfDireccion, 60));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfRut = new javax.swing.JTextField();
        tfVerificador = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfFono = new javax.swing.JTextField();
        tfCorreo = new javax.swing.JTextField();
        tfDireccion = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfBusqueda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jMenuItem1.setText("Editar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setTitle("Proveedores");
        setMinimumSize(new java.awt.Dimension(67, 33));
        setNormalBounds(new java.awt.Rectangle(0, 0, 67, 0));
        setPreferredSize(new java.awt.Dimension(1264, 493));
        setRequestFocusEnabled(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RUT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FONO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CORREO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DIRECCION");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        tfRut.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        tfRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRutActionPerformed(evt);
            }
        });
        getContentPane().add(tfRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 208, -1));

        tfVerificador.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        getContentPane().add(tfVerificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 40, -1));

        tfNombre.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        getContentPane().add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 208, -1));

        tfFono.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        tfFono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFonoKeyTyped(evt);
            }
        });
        getContentPane().add(tfFono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 208, -1));

        tfCorreo.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        getContentPane().add(tfCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 208, -1));

        tfDireccion.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        getContentPane().add(tfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 208, -1));

        btnAgregar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(51, 102, 255));
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 128, -1));

        btnEliminar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(51, 102, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 128, -1));

        btnEditar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(51, 102, 255));
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 128, -1));

        jTable1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut", "Verificador", "Nombre", "Fono", "Correo", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 105, 700, 347));

        tfBusqueda.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        tfBusqueda.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfBusquedaCaretUpdate(evt);
            }
        });
        tfBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(tfBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 50, 614, -1));

        jLabel6.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FLTRAR");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 53, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Layout.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tfRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRutActionPerformed

    private void tfFonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFonoKeyTyped
    }//GEN-LAST:event_tfFonoKeyTyped

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
         // Crear instancia: conexion
        ConexionBD conexion = new ConexionBD();
        Connection con = conexion.conectar();         
              
        try{
            //iniciar la conexion
            conexion.conectar();   
            Statement st = con.createStatement();
            //Sentencia para ingresar proveedores en la BD
            st.executeUpdate("INSERT INTO proveedor (Rut,Verificador,Nombre,Fono,Correo,Direccion) VALUES('"+tfRut.getText()+"','"+tfVerificador.getText()+"','"+tfNombre.getText()+"','"+tfFono.getText()+"','"+tfCorreo.getText()+"','"+tfDireccion.getText()+"')");
              jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut","Verificador", "Nombre", "Fono", "Correo", "Direccion"
            }
        )
      );
              mostrarDatos("");
              Limpiar();
        }catch(Exception ex){
            
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);       
}
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
          // Crear instancia: conexion
        ConexionBD conexion = new ConexionBD();
        Connection con = conexion.conectar();
            //
            int fila = jTable1.getSelectedRow();
            //
            String rut="";
            //
            rut=jTable1.getValueAt(fila, 0).toString();
        try{
            //sentencia para eliminar los datos
            PreparedStatement pst = con.prepareStatement("DELETE FROM proveedor WHERE Rut='"+rut+"'");
            pst.executeUpdate();
                  jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut","Verificador", "Nombre", "Fono", "Correo", "Direccion"
            }
        )
      );
            mostrarDatos("");
            Limpiar();
        }catch(Exception e){
        System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Crear instancia: conexion
        ConexionBD conexion = new ConexionBD();
        Connection con = conexion.conectar();
        try{
            //sentencia para editar los datos
            PreparedStatement pst = con.prepareStatement("UPDATE proveedor SET Rut='"+tfRut.getText()+"',Verificador='"+tfVerificador.getText()+"',Nombre='"+tfNombre.getText()+"',Fono='"+tfFono.getText()+"',Correo='"+tfCorreo.getText()+"',Direccion='"+tfDireccion.getText()+"' WHERE Rut='"+tfRut.getText()+"'");
            pst.executeUpdate();
                  jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut","Verificador", "Nombre", "Fono", "Correo", "Direccion"
            }
        )
      );
            mostrarDatos("");
            Limpiar();
        }catch(Exception e){
        System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Seleccionar fila para editar 
        int fila=jTable1.getSelectedRow();
        if (fila>=0){
            //Seleeciona la fila para mostrarla en el Text Field correspondiente
            tfRut.setText(jTable1.getValueAt(fila,0).toString());
            tfVerificador.setText(jTable1.getValueAt(fila,1).toString());
            tfNombre.setText(jTable1.getValueAt(fila,2).toString());
            tfFono.setText(jTable1.getValueAt(fila,3).toString());
            tfCorreo.setText(jTable1.getValueAt(fila,4).toString());
            tfDireccion.setText(jTable1.getValueAt(fila,5).toString());
            
        }
        else{
        JOptionPane.showMessageDialog(null,"No selecciono fila");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tfBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBusquedaActionPerformed

    }//GEN-LAST:event_tfBusquedaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
 
    }//GEN-LAST:event_jTable1MouseClicked

    private void tfBusquedaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfBusquedaCaretUpdate
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut","Verificador", "Nombre", "Fono", "Correo", "Direccion"
            }
        )
      );
        
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel(); 
       try{
        // Conectar a la BD
        ConexionBD conexion = new ConexionBD();
        Connection con = conexion.conectar();
        //Consulta a ejecutar
        String     sql = ("SELECT * FROM proveedor WHERE (Rut like '%"+tfBusqueda.getText()+"%') or (Nombre like '%"+tfBusqueda.getText()+"%')");
        //Preparar la consulta
        Statement st = con.createStatement();
        //Ejecutar consulta
        ResultSet rs = st.executeQuery(sql);
        //Mostrar los datos
        while(rs.next()){
            String rut = rs.getString("Rut");
            String verif = rs.getString("Verificador");
            String nombre = rs.getString("Nombre");
            String fono = rs.getString("Fono");
            String correo = rs.getString("Correo");
            String direcc = rs.getString("Direccion");
            Object fila []  = {rut, verif, nombre, fono, correo, direcc};
            m.addRow(fila);
        }
        }catch(Exception e){
        System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tfBusquedaCaretUpdate
    
    //Metodo para validar solo numeros
    public void SNumeros (JTextField a){
    //permite hacer la llamada al evento
        //KeyAdapter es una clase abstracta que se adapta para recibir los eventos del teclado
        a.addKeyListener(new KeyAdapter() {
            //Evento a utilizar
            public void keyTyped(KeyEvent e){
            //La variable char extrae la variable que se ingresa
                char c=e.getKeyChar();
                if(Character.isLetter(c)){
                //Sonido en caso que se ingrese un caracter no admitido
                getToolkit().beep();
                e.consume();
                }
            }
        });
    }
    
    private void mostrarDatos(String valor){
    // Crear instancia: conexion
        ConexionBD conexion = new ConexionBD();
        Connection con = conexion.conectar();
    //capturar modelo de la tabla
    DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        jTable1.setModel(m);
    //Acumular sentencia a ejecutar
        String sql="";
        //condicion que compara el valor que se recibe con la sentencia
        if(valor.equals("")){
            sql="SELECT * FROM proveedor";
        }else{
            sql="SELECT * FROM proveedor WHERE RUT='"+valor+"'";
        }
    String [] datos = new String[6];
    try{
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                m.addRow(datos);
            }
            jTable1.setModel(m);
    }catch(SQLException ex){
    Logger.getLogger(JIProveedores.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfBusqueda;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfFono;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfRut;
    private javax.swing.JTextField tfVerificador;
    // End of variables declaration//GEN-END:variables
}
