/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaventas;

/**
 *
 * @author rancagua
 */
public class JIVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIVentas
     */
    public JIVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Fecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        Fecha1 = new javax.swing.JLabel();
        Empleado = new javax.swing.JLabel();
        Fecha2 = new javax.swing.JLabel();
        Fecha3 = new javax.swing.JLabel();
        tfRutCliente = new javax.swing.JTextField();
        tfNombreCliente = new javax.swing.JTextField();
        Fecha4 = new javax.swing.JLabel();
        Fecha5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Fecha6 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();
        btnAgregar2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        NumeroVenta = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setTitle("Ventas");
        setPreferredSize(new java.awt.Dimension(1264, 493));
        setRequestFocusEnabled(false);
        getContentPane().setLayout(null);

        jTable1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° venta", "Producto", "Detalle", "Cantidad", "Precio Unitario", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(492, 60, 750, 330);

        Fecha.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Fecha.setForeground(new java.awt.Color(255, 255, 255));
        Fecha.setText("USTED ES ATENDIDO POR :");
        getContentPane().add(Fecha);
        Fecha.setBounds(430, 10, 180, 50);

        jLabel1.setFont(new java.awt.Font("Impact", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOTAL :$");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(830, 400, 150, 50);

        Total.setFont(new java.awt.Font("Impact", 3, 36)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setText("TOTAL :$");
        getContentPane().add(Total);
        Total.setBounds(990, 400, 150, 50);

        Fecha1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Fecha1.setForeground(new java.awt.Color(255, 255, 255));
        Fecha1.setText("FECHA");
        getContentPane().add(Fecha1);
        Fecha1.setBounds(20, 10, 140, 50);

        Empleado.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Empleado.setForeground(new java.awt.Color(255, 255, 255));
        Empleado.setText("USTED ES ATENDIDO POR :");
        getContentPane().add(Empleado);
        Empleado.setBounds(610, 10, 180, 50);

        Fecha2.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        Fecha2.setForeground(new java.awt.Color(255, 255, 255));
        Fecha2.setText("PRODUCTO");
        getContentPane().add(Fecha2);
        Fecha2.setBounds(150, 250, 220, 50);

        Fecha3.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        Fecha3.setForeground(new java.awt.Color(255, 255, 255));
        Fecha3.setText("CLIENTE");
        getContentPane().add(Fecha3);
        Fecha3.setBounds(170, 70, 160, 50);

        tfRutCliente.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        getContentPane().add(tfRutCliente);
        tfRutCliente.setBounds(160, 130, 230, 37);

        tfNombreCliente.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        getContentPane().add(tfNombreCliente);
        tfNombreCliente.setBounds(160, 180, 230, 37);

        Fecha4.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Fecha4.setForeground(new java.awt.Color(255, 255, 255));
        Fecha4.setText("NOMBRE");
        getContentPane().add(Fecha4);
        Fecha4.setBounds(70, 170, 90, 50);

        Fecha5.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Fecha5.setForeground(new java.awt.Color(255, 255, 255));
        Fecha5.setText("RUT");
        getContentPane().add(Fecha5);
        Fecha5.setBounds(110, 120, 50, 50);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 380, 470, 10);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(10, 60, 470, 10);

        Fecha6.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Fecha6.setForeground(new java.awt.Color(255, 255, 255));
        Fecha6.setText("CODIGO");
        getContentPane().add(Fecha6);
        Fecha6.setBounds(20, 310, 80, 50);

        tfCodigo.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        getContentPane().add(tfCodigo);
        tfCodigo.setBounds(110, 320, 120, 37);

        btnAgregar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(51, 102, 255));
        btnAgregar.setText("Agregar");
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(240, 320, 111, 39);

        btnAgregar1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnAgregar1.setForeground(new java.awt.Color(51, 102, 255));
        btnAgregar1.setText("Quitar");
        getContentPane().add(btnAgregar1);
        btnAgregar1.setBounds(360, 320, 110, 39);

        btnAgregar2.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnAgregar2.setForeground(new java.awt.Color(51, 102, 255));
        btnAgregar2.setText("FACTURAR");
        getContentPane().add(btnAgregar2);
        btnAgregar2.setBounds(190, 400, 140, 39);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(10, 230, 470, 10);

        NumeroVenta.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NumeroVenta.setForeground(new java.awt.Color(255, 255, 255));
        NumeroVenta.setText("numero");
        getContentPane().add(NumeroVenta);
        NumeroVenta.setBounds(1140, 10, 140, 50);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Layout.jpg"))); // NOI18N
        fondo.setPreferredSize(new java.awt.Dimension(1264, 493));
        fondo.setRequestFocusEnabled(false);
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 1270, 493);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Empleado;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Fecha1;
    private javax.swing.JLabel Fecha2;
    private javax.swing.JLabel Fecha3;
    private javax.swing.JLabel Fecha4;
    private javax.swing.JLabel Fecha5;
    private javax.swing.JLabel Fecha6;
    private javax.swing.JLabel NumeroVenta;
    private javax.swing.JLabel Total;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnAgregar2;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfNombreCliente;
    private javax.swing.JTextField tfRutCliente;
    // End of variables declaration//GEN-END:variables
}
