/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaventas;

/**
 *
 * @author rancagua
 */
public class PPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PPrincipal
     */
    public PPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEmpleados = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnDetalles = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnventas = new javax.swing.JButton();
        DP = new javax.swing.JDesktopPane();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1266, 731));
        getContentPane().setLayout(null);

        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btnEmpleados.jpg"))); // NOI18N
        btnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnEmpleados);
        btnEmpleados.setBounds(1010, 70, 160, 50);

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btnCliente.jpg"))); // NOI18N
        btnClientes.setToolTipText("");
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnClientes);
        btnClientes.setBounds(790, 70, 160, 50);
        btnClientes.getAccessibleContext().setAccessibleName("btnClientes");

        btnDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btnDetalle.jpg"))); // NOI18N
        btnDetalles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnDetalles);
        btnDetalles.setBounds(1010, 10, 160, 50);

        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btnProducto.jpg"))); // NOI18N
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnProductos);
        btnProductos.setBounds(790, 10, 160, 50);

        btnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btnProveedor.jpg"))); // NOI18N
        btnProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnProveedor);
        btnProveedor.setBounds(570, 70, 160, 50);

        btnventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btnVentas.jpg"))); // NOI18N
        btnventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnventasActionPerformed(evt);
            }
        });
        getContentPane().add(btnventas);
        btnventas.setBounds(570, 10, 160, 50);

        javax.swing.GroupLayout DPLayout = new javax.swing.GroupLayout(DP);
        DP.setLayout(DPLayout);
        DPLayout.setHorizontalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );
        DPLayout.setVerticalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        getContentPane().add(DP);
        DP.setBounds(0, 130, 1270, 490);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/layout Principal.jpg"))); // NOI18N
        Fondo.setText("jLabel1");
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 1266, 731);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventasActionPerformed
        // Crear instancia ventas
        JIVentas ventas = new JIVentas();
        DP.add(ventas);
        ventas.setVisible(true);
    }//GEN-LAST:event_btnventasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DP;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnventas;
    // End of variables declaration//GEN-END:variables
}
